package com.example.myapplication.app;

/**
 * Created by gdh1995 on 2015/11/16.
 */
public class IlsvrcLabels {
    static final String[] labels = {
            "tench, Tinca tinca",
            "goldfish, Carassius auratus",
            "shark, white shark, man-eater, man-eating shark, Carcharodon carcharias",
            "shark, Galeocerdo cuvieri",
            "hammerhead, hammerhead shark",
            "ray, crampfish, numbfish, torpedo",
            "stingray",
            "cock",
            "hen",
            "ostrich, Struthio camelus",
            "brambling, Fringilla montifringilla",
            "goldfinch, Carduelis carduelis",
            "finch, linnet, Carpodacus mexicanus",
            "junco, snowbird",
            "bunting, indigo finch, indigo bird, Passerina cyanea",
            "robin, American robin, Turdus migratorius",
            "bulbul",
            "jay",
            "magpie",
            "chickadee",
            "ouzel, dipper",
            "kite",
            "eagle, American eagle, Haliaeetus leucocephalus",
            "vulture",
            "owl, great gray owl, Strix nebulosa",
            "salamander, Salamandra salamandra",
            "newt, Triturus vulgaris",
            "eft",
            "salamander, Ambystoma maculatum",
            "axolotl, mud puppy, Ambystoma mexicanum",
            "bullfrog, Rana catesbeiana",
            "frog, tree-frog",
            "frog, bell toad, ribbed toad, tailed toad, Ascaphus trui",
            "loggerhead, loggerhead turtle, Caretta caretta",
            "turtle, leatherback, leathery turtle, Dermochelys coriacea",
            "turtle",
            "terrapin",
            "turtle, box tortoise",
            "gecko",
            "iguana, iguana, Iguana iguana",
            "chameleon, anole, Anolis carolinensis",
            "whiptail, whiptail lizard",
            "agama",
            "lizard, Chlamydosaurus kingi",
            "lizard",
            "monster, Heloderma suspectum",
            "lizard, Lacerta viridis",
            "chameleon, Chamaeleo chamaeleon",
            "dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis",
            "crocodile, Nile crocodile, Crocodylus niloticus",
            "alligator, Alligator mississipiensis",
            "triceratops",
            "snake, worm snake, Carphophis amoenus",
            "snake, ring-necked snake, ring snake",
            "snake, puff adder, sand viper",
            "snake, grass snake",
            "snake, kingsnake",
            "snake, grass snake",
            "snake",
            "snake",
            "snake, Hypsiglena torquata",
            "constrictor, Constrictor constrictor",
            "python, rock snake, Python sebae",
            "cobra, Naja naja",
            "mamba",
            "snake",
            "viper, cerastes, sand viper, horned asp, Cerastes cornutus",
            "diamondback, diamondback rattlesnake, Crotalus adamanteus",
            "sidewinder, horned rattlesnake, Crotalus cerastes",
            "trilobite",
            "harvestman, daddy longlegs, Phalangium opilio",
            "scorpion",
            "spider, Argiope aurantia",
            "spider, Araneus cavaticus",
            "spider, Aranea diademata",
            "widow, Latrodectus mactans",
            "tarantula",
            "spider, hunting spider",
            "tick",
            "centipede",
            "grouse",
            "ptarmigan",
            "grouse, partridge, Bonasa umbellus",
            "chicken, prairie grouse, prairie fowl",
            "peacock",
            "quail",
            "partridge",
            "grey, African gray, Psittacus erithacus",
            "macaw",
            "sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita",
            "lorikeet",
            "coucal",
            "eater",
            "hornbill",
            "hummingbird",
            "jacamar",
            "toucan",
            "drake",
            "red-breasted merganser, Mergus serrator",
            "goose",
            "swan, Cygnus atratus",
            "tusker",
            "echidna, spiny anteater, anteater",
            "platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus",
            "wallaby, brush kangaroo",
            "koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus",
            "wombat",
            "jellyfish",
            "anemone, anemone",
            "coral",
            "flatworm, platyhelminth",
            "nematode, nematode worm, roundworm",
            "conch",
            "snail",
            "slug",
            "slug, nudibranch",
            "chiton, coat-of-mail shell, sea cradle, polyplacophore",
            "nautilus, pearly nautilus, nautilus",
            "crab, Cancer magister",
            "crab, Cancer irroratus",
            "crab",
            "crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica",
            "lobster, Northern lobster, Maine lobster, Homarus americanus",
            "lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish",
            "crayfish, crawfish, crawdad, crawdaddy",
            "crab",
            "isopod",
            "stork, Ciconia ciconia",
            "stork, Ciconia nigra",
            "spoonbill",
            "flamingo",
            "heron, Egretta caerulea",
            "egret, great white heron, Egretta albus",
            "bittern",
            "crane",
            "limpkin, Aramus pictus",
            "gallinule, Porphyrio porphyrio",
            "coot, marsh hen, mud hen, water hen, Fulica americana",
            "bustard",
            "turnstone, Arenaria interpres",
            "red-backed sandpiper, dunlin, Erolia alpina",
            "redshank, Tringa totanus",
            "dowitcher",
            "oystercatcher, oyster catcher",
            "pelican",
            "penguin, Aptenodytes patagonica",
            "albatross, mollymawk",
            "whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus",
            "whale, killer, orca, grampus, sea wolf, Orcinus orca",
            "dugong, Dugong dugon",
            "lion",
            "Chihuahua",
            "spaniel",
            "dog, Maltese terrier, Maltese",
            "Pekinese, Pekingese, Peke",
            "Shih-Tzu",
            "spaniel",
            "papillon",
            "terrier",
            "ridgeback",
            "hound, Afghan",
            "basset, basset hound",
            "beagle",
            "bloodhound, sleuthhound",
            "bluetick",
            "black-and-tan coonhound",
            "hound, Walker foxhound",
            "foxhound",
            "redbone",
            "borzoi, Russian wolfhound",
            "wolfhound",
            "greyhound",
            "whippet",
            "hound, Ibizan Podenco",
            "elkhound, elkhound",
            "otterhound, otter hound",
            "Saluki, gazelle hound",
            "deerhound, deerhound",
            "Weimaraner",
            "bullterrier, Staffordshire bull terrier",
            "terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier",
            "terrier",
            "terrier",
            "terrier",
            "terrier",
            "terrier",
            "terrier",
            "terrier",
            "wire-haired fox terrier",
            "terrier",
            "terrier, Sealyham",
            "Airedale, Airedale terrier",
            "cairn, cairn terrier",
            "terrier",
            "Dinmont, Dandie Dinmont terrier",
            "bull, Boston terrier",
            "schnauzer",
            "schnauzer",
            "schnauzer",
            "terrier, Scottish terrier, Scottie",
            "terrier, chrysanthemum dog",
            "terrier, Sydney silky",
            "soft-coated wheaten terrier",
            "terrier",
            "Lhasa, Lhasa apso",
            "flat-coated retriever",
            "curly-coated retriever",
            "retriever",
            "retriever",
            "retriever",
            "short-haired pointer",
            "vizsla, Hungarian pointer",
            "setter",
            "setter, red setter",
            "setter",
            "spaniel",
            "clumber, clumber spaniel",
            "springer, English springer spaniel",
            "spaniel",
            "spaniel, English cocker spaniel, cocker",
            "spaniel",
            "spaniel",
            "kuvasz",
            "schipperke",
            "groenendael",
            "malinois",
            "briard",
            "kelpie",
            "komondor",
            "sheepdog, bobtail",
            "sheepdog, Shetland sheep dog, Shetland",
            "collie",
            "collie",
            "Flandres, Bouviers des Flandres",
            "Rottweiler",
            "shepherd, German shepherd dog, German police dog, alsatian",
            "Doberman, Doberman pinscher",
            "pinscher",
            "dog",
            "dog",
            "Appenzeller",
            "EntleBucher",
            "boxer",
            "mastiff",
            "mastiff",
            "bulldog",
            "Dane",
            "Bernard, St Bernard",
            "dog, husky",
            "malamute, malemute, Alaskan malamute",
            "husky",
            "dalmatian, coach dog, carriage dog",
            "affenpinscher, monkey pinscher, monkey dog",
            "basenji",
            "pug, pug-dog",
            "Leonberg",
            "Newfoundland, Newfoundland dog",
            "Pyrenees",
            "Samoyed, Samoyede",
            "Pomeranian",
            "chow, chow chow",
            "keeshond",
            "griffon",
            "Pembroke, Pembroke Welsh corgi",
            "Cardigan, Cardigan Welsh corgi",
            "poodle",
            "poodle",
            "poodle",
            "hairless",
            "wolf, grey wolf, gray wolf, Canis lupus",
            "wolf, Arctic wolf, Canis lupus tundrarum",
            "wolf, maned wolf, Canis rufus, Canis niger",
            "coyote, prairie wolf, brush wolf, Canis latrans",
            "dingo, warrigal, warragal, Canis dingo",
            "dhole, Cuon alpinus",
            "dog, hyena dog, Cape hunting dog, Lycaon pictus",
            "hyena, hyaena",
            "fox, Vulpes vulpes",
            "fox, Vulpes macrotis",
            "fox, white fox, Alopex lagopus",
            "fox, gray fox, Urocyon cinereoargenteus",
            "tabby, tabby cat",
            "cat",
            "cat",
            "cat, Siamese",
            "cat",
            "cougar, puma, catamount, mountain lion, painter, panther, Felis concolor",
            "lynx, catamount",
            "leopard, Panthera pardus",
            "leopard, ounce, Panthera uncia",
            "jaguar, panther, Panthera onca, Felis onca",
            "lion, king of beasts, Panthera leo",
            "tiger, Panthera tigris",
            "cheetah, chetah, Acinonyx jubatus",
            "bear, bruin, Ursus arctos",
            "bear, black bear, Ursus americanus, Euarctos americanus",
            "bear, polar bear, Ursus Maritimus, Thalarctos maritimus",
            "bear, Melursus ursinus, Ursus ursinus",
            "mongoose",
            "meerkat, mierkat",
            "beetle",
            "ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle",
            "beetle, carabid beetle",
            "long-horned beetle, longicorn, longicorn beetle",
            "beetle, chrysomelid",
            "beetle",
            "beetle",
            "weevil",
            "fly",
            "bee",
            "ant, emmet, pismire",
            "grasshopper, hopper",
            "cricket",
            "stick, walkingstick, stick insect",
            "cockroach, roach",
            "mantis, mantid",
            "cicada, cicala",
            "leafhopper",
            "lacewing, lacewing fly",
            "dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk",
            "damselfly",
            "admiral",
            "ringlet, ringlet butterfly",
            "monarch, monarch butterfly, milkweed butterfly, Danaus plexippus",
            "butterfly",
            "butterfly, sulfur butterfly",
            "lycaenid, lycaenid butterfly",
            "starfish, sea star",
            "urchin",
            "cucumber, holothurian",
            "rabbit, cottontail, cottontail rabbit",
            "hare",
            "Angora, Angora rabbit",
            "hamster",
            "porcupine, hedgehog",
            "squirrel, eastern fox squirrel, Sciurus niger",
            "marmot",
            "beaver",
            "pig, Cavia cobaya",
            "sorrel",
            "zebra",
            "hog, pig, grunter, squealer, Sus scrofa",
            "boar, boar, Sus scrofa",
            "warthog",
            "hippopotamus, hippo, river horse, Hippopotamus amphibius",
            "ox",
            "buffalo, water ox, Asiatic buffalo, Bubalus bubalis",
            "bison",
            "ram, tup",
            "bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis",
            "ibex, Capra ibex",
            "hartebeest",
            "impala, Aepyceros melampus",
            "gazelle",
            "camel, dromedary, Camelus dromedarius",
            "llama",
            "weasel",
            "mink",
            "polecat, fitch, foulmart, foumart, Mustela putorius",
            "black-footed ferret, ferret, Mustela nigripes",
            "otter",
            "skunk, polecat, wood pussy",
            "badger",
            "armadillo",
            "three-toed sloth, ai, Bradypus tridactylus",
            "orangutan, orang, orangutang, Pongo pygmaeus",
            "gorilla, Gorilla gorilla",
            "chimpanzee, chimp, Pan troglodytes",
            "gibbon, Hylobates lar",
            "siamang, Hylobates syndactylus, Symphalangus syndactylus",
            "guenon, guenon monkey",
            "patas, hussar monkey, Erythrocebus patas",
            "baboon",
            "macaque",
            "langur",
            "colobus, colobus monkey",
            "monkey, Nasalis larvatus",
            "marmoset",
            "capuchin, ringtail, Cebus capucinus",
            "monkey, howler",
            "titi, titi monkey",
            "monkey, Ateles geoffroyi",
            "monkey, Saimiri sciureus",
            "cat, ring-tailed lemur, Lemur catta",
            "indri, indris, Indri indri, Indri brevicaudatus",
            "elephant, Elephas maximus",
            "elephant, Loxodonta africana",
            "panda, red panda, panda, bear cat, cat bear, Ailurus fulgens",
            "panda, panda, panda bear, coon bear, Ailuropoda melanoleuca",
            "barracouta, snoek",
            "eel",
            "coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch",
            "beauty, Holocanthus tricolor",
            "fish",
            "sturgeon",
            "gar, garfish, garpike, billfish, Lepisosteus osseus",
            "lionfish",
            "puffer, pufferfish, blowfish, globefish",
            "abacus",
            "abaya",
            "gown, academic robe, judge's robe",
            "accordion, piano accordion, squeeze box",
            "guitar",
            "carrier, carrier, flattop, attack aircraft carrier",
            "airliner",
            "airship, dirigible",
            "altar",
            "ambulance",
            "amphibian, amphibious vehicle",
            "clock",
            "apiary, bee house",
            "apron",
            "ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin",
            "rifle, assault gun",
            "backpack, back pack, knapsack, packsack, rucksack, haversack",
            "bakery, bakeshop, bakehouse",
            "beam, beam",
            "balloon",
            "ballpoint, ballpoint pen, ballpen, Biro",
            "Aid",
            "banjo",
            "bannister, banister, balustrade, balusters, handrail",
            "barbell",
            "chair",
            "barbershop",
            "barn",
            "barometer",
            "barrel, cask",
            "barrow, garden cart, lawn cart, wheelbarrow",
            "baseball",
            "basketball",
            "bassinet",
            "bassoon",
            "cap, swimming cap",
            "towel",
            "bathtub, bathing tub, bath, tub",
            "wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon",
            "beacon, lighthouse, beacon light, pharos",
            "beaker",
            "bearskin, busby, shako",
            "bottle",
            "glass",
            "cote, bell cot",
            "bib",
            "bicycle-built-for-two, tandem bicycle, tandem",
            "bikini, two-piece",
            "binder, ring-binder",
            "binoculars, field glasses, opera glasses",
            "birdhouse",
            "boathouse",
            "bobsled, bobsleigh, bob",
            "tie, bolo, bola tie, bola",
            "bonnet, poke bonnet",
            "bookcase",
            "bookshop, bookstore, bookstall",
            "bottlecap",
            "bow",
            "tie, bow-tie, bowtie",
            "brass, memorial tablet, plaque",
            "brassiere, bra, bandeau",
            "breakwater, groin, groyne, mole, bulwark, seawall, jetty",
            "breastplate, aegis, egis",
            "broom",
            "bucket, pail",
            "buckle",
            "vest",
            "train, bullet",
            "shop, meat market",
            "cab, hack, taxi, taxicab",
            "caldron, cauldron",
            "candle, taper, wax light",
            "cannon",
            "canoe",
            "opener, tin opener",
            "cardigan",
            "mirror",
            "carousel, carrousel, merry-go-round, roundabout, whirligig",
            "carpenter's kit, tool kit",
            "carton",
            "wheel",
            "machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
            "cassette",
            "player",
            "castle",
            "catamaran",
            "player",
            "cello, violoncello",
            "telephone, cellular phone, cellphone, cell, mobile phone",
            "chain",
            "fence",
            "mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour",
            "saw, chainsaw",
            "chest",
            "chiffonier, commode",
            "chime, bell, gong",
            "cabinet, china closet",
            "stocking",
            "church, church building",
            "cinema, movie theater, movie theatre, movie house, picture palace",
            "cleaver, meat cleaver, chopper",
            "dwelling",
            "cloak",
            "clog, geta, patten, sabot",
            "shaker",
            "mug",
            "coffeepot",
            "coil, spiral, volute, whorl, helix",
            "lock",
            "keyboard, keypad",
            "confectionery, confectionary, candy store",
            "ship, containership, container vessel",
            "convertible",
            "corkscrew, bottle screw",
            "cornet, horn, trumpet, trump",
            "boot",
            "hat, ten-gallon hat",
            "cradle",
            "crane",
            "helmet",
            "crate",
            "crib, cot",
            "Pot",
            "ball",
            "crutch",
            "cuirass",
            "dam, dike, dyke",
            "desk",
            "computer",
            "telephone, dial phone",
            "diaper, nappy, napkin",
            "clock",
            "watch",
            "table, board",
            "dishrag, dishcloth",
            "dishwasher, dish washer, dishwashing machine",
            "brake, disc brake",
            "dock, dockage, docking facility",
            "dogsled, dog sled, dog sleigh",
            "dome",
            "doormat, welcome mat",
            "platform, offshore rig",
            "drum, membranophone, tympan",
            "drumstick",
            "dumbbell",
            "oven",
            "fan, blower",
            "guitar",
            "locomotive",
            "center",
            "envelope",
            "maker",
            "powder",
            "boa, boa",
            "file, file cabinet, filing cabinet",
            "fireboat",
            "engine, fire truck",
            "screen, fireguard",
            "flagpole, flagstaff",
            "flute, transverse flute",
            "chair",
            "helmet",
            "forklift",
            "fountain",
            "pen",
            "four-poster",
            "car",
            "horn, horn",
            "pan, frypan, skillet",
            "coat",
            "truck, dustcart",
            "gasmask, respirator, gas helmet",
            "pump, gasoline pump, petrol pump, island dispenser",
            "goblet",
            "go-kart",
            "ball",
            "golfcart, golf cart",
            "gondola",
            "gong, tam-tam",
            "gown",
            "piano, grand",
            "greenhouse, nursery, glasshouse",
            "grille, radiator grille",
            "store, grocery, food market, market",
            "guillotine",
            "slide",
            "spray",
            "track",
            "hammer",
            "hamper",
            "blower, blow dryer, blow drier, hair dryer, hair drier",
            "hand-held computer, hand-held microcomputer",
            "handkerchief, hankie, hanky, hankey",
            "disc, hard disk, fixed disk",
            "harmonica, mouth organ, harp, mouth harp",
            "harp",
            "harvester, reaper",
            "hatchet",
            "holster",
            "theater, home theatre",
            "honeycomb",
            "hook, claw",
            "hoopskirt, crinoline",
            "bar, high bar",
            "cart, horse-cart",
            "hourglass",
            "iPod",
            "iron, smoothing iron",
            "jack-o'-lantern",
            "jean, blue jean, denim",
            "jeep, landrover",
            "jersey, T-shirt, tee shirt",
            "puzzle",
            "jinrikisha, ricksha, rickshaw",
            "joystick",
            "kimono",
            "pad",
            "knot",
            "coat, laboratory coat",
            "ladle",
            "lampshade, lamp shade",
            "laptop, laptop computer",
            "mower, mower",
            "cap, lens cover",
            "opener, paper knife, paperknife",
            "library",
            "lifeboat",
            "lighter, light, igniter, ignitor",
            "limousine, limo",
            "liner, ocean liner",
            "lipstick, lip rouge",
            "Loafer",
            "lotion",
            "loudspeaker, speaker, speaker unit, loudspeaker system, speaker system",
            "loupe, jeweler's loupe",
            "lumbermill, sawmill",
            "compass",
            "mailbag, postbag",
            "mailbox, letter box",
            "maillot",
            "maillot, tank suit",
            "cover",
            "maraca",
            "marimba, xylophone",
            "mask",
            "matchstick",
            "maypole",
            "maze, labyrinth",
            "cup",
            "chest, medicine cabinet",
            "megalith, megalithic structure",
            "microphone, mike",
            "microwave, microwave oven",
            "uniform",
            "can",
            "minibus",
            "miniskirt, mini",
            "minivan",
            "missile",
            "mitten",
            "bowl",
            "home, manufactured home",
            "T",
            "modem",
            "monastery",
            "monitor",
            "moped",
            "mortar",
            "mortarboard",
            "mosque",
            "net",
            "scooter, scooter",
            "bike, all-terrain bike, off-roader",
            "tent",
            "mouse, computer mouse",
            "mousetrap",
            "van",
            "muzzle",
            "nail",
            "brace",
            "necklace",
            "nipple",
            "notebook, notebook computer",
            "obelisk",
            "oboe, hautboy, hautbois",
            "ocarina, sweet potato",
            "odometer, hodometer, mileometer, milometer",
            "filter",
            "organ, pipe organ",
            "oscilloscope, scope, cathode-ray oscilloscope, CRO",
            "overskirt",
            "oxcart",
            "mask",
            "packet",
            "paddle, boat paddle",
            "paddlewheel, paddle wheel",
            "padlock",
            "paintbrush",
            "pajama, pyjama, pj's, jammies",
            "palace",
            "panpipe, pandean pipe, syrinx",
            "towel",
            "parachute, chute",
            "bars, bars",
            "bench",
            "meter",
            "car, coach, carriage",
            "patio, terrace",
            "pay-phone, pay-station",
            "pedestal, plinth, footstall",
            "box, pencil case",
            "sharpener",
            "perfume, essence",
            "dish",
            "photocopier",
            "pick, plectrum, plectron",
            "pickelhaube",
            "fence, paling",
            "pickup, pickup truck",
            "pier",
            "bank, penny bank",
            "bottle",
            "pillow",
            "ping-pong ball",
            "pinwheel",
            "pirate, pirate ship",
            "pitcher, ewer",
            "plane, carpenter's plane, woodworking plane",
            "planetarium",
            "bag",
            "rack",
            "plow, plough",
            "plunger, plumber's helper",
            "camera, Polaroid Land camera",
            "pole",
            "van, police wagon, paddy wagon, patrol wagon, wagon, black Maria",
            "poncho",
            "table, billiard table, snooker table",
            "bottle, soda bottle",
            "pot, flowerpot",
            "potter's wheel",
            "drill",
            "rug, prayer mat",
            "printer",
            "prison, prison house",
            "projectile, missile",
            "projector",
            "puck, hockey puck",
            "bag, punch bag, punching ball, punchball",
            "purse",
            "quill, quill pen",
            "quilt, comforter, comfort, puff",
            "racer, race car, racing car",
            "racket, racquet",
            "radiator",
            "radio, wireless",
            "telescope, radio reflector",
            "barrel",
            "vehicle, RV, R.V.",
            "reel",
            "camera",
            "refrigerator, icebox",
            "control, remote",
            "restaurant, eating house, eating place, eatery",
            "revolver, six-gun, six-shooter",
            "rifle",
            "chair, rocker",
            "rotisserie",
            "eraser, rubber, pencil eraser",
            "ball",
            "rule, ruler",
            "shoe",
            "safe",
            "pin",
            "saltshaker, salt shaker",
            "sandal",
            "sarong",
            "sax, saxophone",
            "scabbard",
            "scale, weighing machine",
            "bus",
            "schooner",
            "scoreboard",
            "screen, CRT screen",
            "screw",
            "screwdriver",
            "belt, seatbelt",
            "machine",
            "shield, buckler",
            "shop, shoe-shop, shoe store",
            "shoji",
            "basket",
            "cart",
            "shovel",
            "cap",
            "curtain",
            "ski",
            "mask",
            "bag",
            "rule, slipstick",
            "door",
            "slot, one-armed bandit",
            "snorkel",
            "snowmobile",
            "snowplow, snowplough",
            "dispenser",
            "ball",
            "sock",
            "dish, solar collector, solar furnace",
            "sombrero",
            "bowl",
            "bar",
            "heater",
            "shuttle",
            "spatula",
            "speedboat",
            "web, spider's web",
            "spindle",
            "car, sport car",
            "spotlight, spot",
            "stage",
            "locomotive",
            "bridge",
            "drum",
            "stethoscope",
            "stole",
            "wall",
            "stopwatch, stop watch",
            "stove",
            "strainer",
            "streetcar, tram, tramcar, trolley, trolley car",
            "stretcher",
            "couch, day bed",
            "stupa, tope",
            "submarine, pigboat, sub, U-boat",
            "suit, suit of clothes",
            "sundial",
            "sunglass",
            "sunglasses, dark glasses, shades",
            "sunscreen, sunblock, sun blocker",
            "bridge",
            "swab, swob, mop",
            "sweatshirt",
            "trunks, bathing trunks",
            "swing",
            "switch, electric switch, electrical switch",
            "syringe",
            "lamp",
            "tank, army tank, armored combat vehicle, armoured combat vehicle",
            "player",
            "teapot",
            "teddy, teddy bear",
            "television, television system",
            "ball",
            "thatch, thatched roof",
            "curtain, theatre curtain",
            "thimble",
            "thresher, thrasher, threshing machine",
            "throne",
            "roof",
            "toaster",
            "shop, tobacconist shop, tobacconist",
            "seat",
            "torch",
            "pole",
            "truck, tow car, wrecker",
            "toyshop",
            "tractor",
            "truck, tractor trailer, trucking rig, rig, articulated lorry, semi",
            "tray",
            "coat",
            "tricycle, trike, velocipede",
            "trimaran",
            "tripod",
            "arch",
            "trolleybus, trolley coach, trackless trolley",
            "trombone",
            "tub, vat",
            "turnstile",
            "keyboard",
            "umbrella",
            "unicycle, monocycle",
            "upright, upright piano",
            "vacuum, vacuum cleaner",
            "vase",
            "vault",
            "velvet",
            "machine",
            "vestment",
            "viaduct",
            "violin, fiddle",
            "volleyball",
            "iron",
            "clock",
            "wallet, billfold, notecase, pocketbook",
            "wardrobe, closet, press",
            "warplane, military plane",
            "washbasin, handbasin, washbowl, lavabo, wash-hand basin",
            "washer, automatic washer, washing machine",
            "bottle",
            "jug",
            "tower",
            "jug",
            "whistle",
            "wig",
            "screen",
            "shade",
            "tie",
            "bottle",
            "wing",
            "wok",
            "spoon",
            "wool, woolen, woollen",
            "fence, snake fence, snake-rail fence, Virginia fence",
            "wreck",
            "yawl",
            "yurt",
            "site, website, internet site, site",
            "book",
            "puzzle, crossword",
            "sign",
            "light, traffic signal, stoplight",
            "jacket, dust cover, dust jacket, dust wrapper",
            "menu",
            "plate",
            "guacamole",
            "consomme",
            "pot, hotpot",
            "trifle",
            "cream, icecream",
            "lolly, lolly, lollipop, popsicle",
            "loaf",
            "bagel, beigel",
            "pretzel",
            "cheeseburger",
            "hotdog, hot dog, red hot",
            "potato",
            "cabbage",
            "broccoli",
            "cauliflower",
            "zucchini, courgette",
            "squash",
            "squash",
            "squash",
            "cucumber, cuke",
            "artichoke, globe artichoke",
            "pepper",
            "cardoon",
            "mushroom",
            "Smith",
            "strawberry",
            "orange",
            "lemon",
            "fig",
            "pineapple, ananas",
            "banana",
            "jackfruit, jak, jack",
            "apple",
            "pomegranate",
            "hay",
            "carbonara",
            "sauce, chocolate syrup",
            "dough",
            "loaf, meatloaf",
            "pizza, pizza pie",
            "potpie",
            "burrito",
            "wine",
            "espresso",
            "cup",
            "eggnog",
            "alp",
            "bubble",
            "cliff, drop, drop-off",
            "reef",
            "geyser",
            "lakeside, lakeshore",
            "promontory, headland, head, foreland",
            "sandbar, sand bar",
            "seashore, coast, seacoast, sea-coast",
            "valley, vale",
            "volcano",
            "ballplayer, baseball player",
            "groom, bridegroom",
            "diver",
            "rapeseed",
            "daisy",
            "lady's slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum",
            "corn",
            "acorn",
            "hip, rose hip, rosehip",
            "buckeye, horse chestnut, conker",
            "fungus",
            "agaric",
            "gyromitra",
            "stinkhorn, carrion fungus",
            "earthstar",
            "hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa",
            "bolete",
            "ear, spike, capitulum",
            "tissue, toilet paper, bathroom tissue"
    };
}
